name: Fetch Random User
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */2 * * *'

    
jobs:
  fetch_random_user:
    name: Fetch and Update
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        id: request
        uses: fjogeleit/http-request-action@v1.12.0
        with:
          url: 'https://anime-hot-take.vercel.app/api/hot-take'
          method: 'GET'
          timeout: 30000
      - name: Response
        run: |
          echo "Current mean: ${{ fromJson(steps.request.outputs.response).mean }}" >> $GITHUB_STEP_SUMMARY
