name: Fetch Random User
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */2 * * *'

    
jobs:
  fetch_random_user:
    name: Fetch and Update
    runs-on: ubuntu-latest
    steps:
      - name: Get Random user
        id: randomUser
        uses: fjogeleit/http-request-action@v1.12.0
        with:
          url: 'https://api.jikan.moe/v4/random/users'
          method: 'GET'
          timeout: 20000
      - name: Get Score
        id: request
        uses: fjogeleit/http-request-action@v1.12.0
        with:
          url: 'https://anime-hot-take.vercel.app/api/hot-take?user=${{ fromJson(steps.randomUser.outputs.response).data.username }}'
          method: 'GET'
          timeout: 10000
      - name: Response
        run: |
          echo "New mean: ${{ fromJson(steps.request.outputs.response).mean }}" >> $GITHUB_STEP_SUMMARY >> $GITHUB_STEP_SUMMARY
