name: Fetch Random User
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 12,20 * * *'

    
jobs:
  fetch_random_user:
    name: Fetch and Update
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        id: requestStep
        uses: fjogeleit/http-request-action@v1.12.0
        with:
          url: 'https://anime-hot-take.vercel.app/api/hot-take'
      - name: Response
        run: |
          echo ${{ steps.requestStep.outputs.response }}
